# Generated by Django 4.1.3 on 2022-12-02 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(max_length=5)),
                ('total_deposits', models.FloatField()),
                ('total_invested', models.FloatField()),
                ('available_capital', models.FloatField()),
                ('current_value', models.FloatField()),
                ('nb_shares', models.FloatField()),
                ('roi', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
