# Generated by Django 4.1.3 on 2022-12-02 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_position'),
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountdata',
            name='account_id',
        ),
        migrations.AddField(
            model_name='accountdata',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='data_points', to='accounts.account'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accountdata',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
