site_name: savings
site_description: A place to keep track of all your portfolio
repo_url: https://github.com/SamuelPerron/savings
site_dir: site
copyright: Copyright &copy; 2020, <a href="https://github.com/SamuelPerron">SamuelPerron</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
