# Generated by Django 4.1.3 on 2022-12-01 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_deposit_date'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='security',
            options={'verbose_name_plural': 'securities'},
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_allocation', models.FloatField(default=0)),
                ('is_fractional', models.BooleanField(default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='accounts.account')),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='transactions.security')),
            ],
        ),
    ]
