# Generated by Django 4.1.3 on 2022-12-01 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_transaction_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='leftovers',
            field=models.FloatField(default=0),
        ),
    ]
