# Generated by Django 4.1.3 on 2022-12-01 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_position_leftovers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Position',
        ),
    ]
